apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: two4onebill/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              #value: 'story'  #can define the value here or can get the value from another .yaml file using a configMap (i.e. the environment.yaml file that we added)
              valueFrom:
                configMapKeyRef: 
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume # defined below in volumes list
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
