apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv  #connects to the specific volume, make sure you use the name in hte persistent volume configuration (i.e. here its defined in the host-pv.yaml file)
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
